NATIONALITY_CHOICES = (
    ("Afghan", "Afghan"),
    ("Åland Island", "Åland Island"),
    ("Albanian", "Albanian"),
    ("Algerian", "Algerian"),
    ("American Samoan", "American Samoan"),
    ("Andorran", "Andorran"),
    ("Angolan", "Angolan"),
    ("Anguillan", "Anguillan"),
    ("Antarctic", "Antarctic"),
    ("Antiguan or Barbudan", "Antiguan or Barbudan"),
    ("Argentine", "Argentine"),
    ("Armenian", "Armenian"),
    ("Aruban", "Aruban"),
    ("Australian", "Australian"),
    ("Austrian", "Austrian"),
    ("Azerbaijani, Azeri", "Azerbaijani, Azeri"),
    ("Bahamian", "Bahamian"),
    ("Bahraini", "Bahraini"),
    ("Bangladeshi", "Bangladeshi"),
    ("Barbadian", "Barbadian"),
    ("Belarusian", "Belarusian"),
    ("Belgian", "Belgian"),
    ("Belizean", "Belizean"),
    ("Beninese, Beninois", "Beninese, Beninois"),
    ("Bermudian, Bermudan", "Bermudian, Bermudan"),
    ("Bhutanese", "Bhutanese"),
    ("Bolivian", "Bolivian"),
    ("Bonaire", "Bonaire"),
    ("Bosnian or Herzegovinian", "Bosnian or Herzegovinian"),
    ("Motswana, Botswanan", "Motswana, Botswanan"),
    ("Bouvet Island", "Bouvet Island"),
    ("Brazilian", "Brazilian"),
    ("BIOT", "BIOT"),
    ("Bruneian", "Bruneian"),
    ("Bulgarian", "Bulgarian"),
    ("Burkinabé", "Burkinabé"),
    ("Burundian", "Burundian"),
    ("Cabo Verdean", "Cabo Verdean"),
    ("Cambodian", "Cambodian"),
    ("Cameroonian", "Cameroonian"),
    ("Canadian", "Canadian"),
    ("Caymanian", "Caymanian"),
    ("Central African", "Central African"),
    ("Chadian", "Chadian"),
    ("Chilean", "Chilean"),
    ("Chinese", "Chinese"),
    ("Christmas Island", "Christmas Island"),
    ("Cocos Island", "Cocos Island"),
    ("Colombian", "Colombian"),
    ("Comoran, Comorian", "Comoran, Comorian"),
    ("Congolese", "Congolese"),
    ("Congolese", "Congolese"),
    ("Cook Island", "Cook Island"),
    ("Costa Rican", "Costa Rican"),
    ("Ivorian", "Ivorian"),
    ("Croatian", "Croatian"),
    ("Cuban", "Cuban"),
    ("Cura\u00e7aoan", "Cura\u00e7aoan"),
    ("Cypriot", "Cypriot"),
    ("Czech", "Czech"),
    ("Danish", "Danish"),
    ("Djiboutian", "Djiboutian"),
    ("Dominican", "Dominican"),
    ("Dominican", "Dominican"),
    ("Ecuadorian", "Ecuadorian"),
    ("Egyptian", "Egyptian"),
    ("Salvadoran", "Salvadoran"),
    ("Equatorial Guinean, Equatoguinean", "Equatorial Guinean, Equatoguinean"),
    ("Eritrean", "Eritrean"),
    ("Estonian", "Estonian"),
    ("Ethiopian", "Ethiopian"),
    ("Falkland Island", "Falkland Island"),
    ("Faroese", "Faroese"),
    ("Fijian", "Fijian"),
    ("Finnish", "Finnish"),
    ("French", "French"),
    ("French Guianese", "French Guianese"),
    ("French Polynesian", "French Polynesian"),
    ("French Southern Territories", "French Southern Territories"),
    ("Gabonese", "Gabonese"),
    ("Gambian", "Gambian"),
    ("Georgian", "Georgian"),
    ("German", "German"),
    ("Ghanaian", "Ghanaian"),
    ("Gibraltar", "Gibraltar"),
    ("Greek, Hellenic", "Greek, Hellenic"),
    ("Greenlandic", "Greenlandic"),
    ("Grenadian", "Grenadian"),
    ("Guadeloupe", "Guadeloupe"),
    ("Guamanian, Guambat", "Guamanian, Guambat"),
    ("Guatemalan", "Guatemalan"),
    ("Channel Island", "Channel Island"),
    ("Guinean", "Guinean"),
    ("Bissau-Guinean", "Bissau-Guinean"),
    ("Guyanese", "Guyanese"),
    ("Haitian", "Haitian"),
    ("Heard Island or McDonald Islands", "Heard Island or McDonald Islands"),
    ("Vatican", "Vatican"),
    ("Honduran", "Honduran"),
    ("Hong Kong, Hong Kongese", "Hong Kong, Hong Kongese"),
    ("Hungarian, Magyar", "Hungarian, Magyar"),
    ("Icelandic", "Icelandic"),
    ("Indian", "Indian"),
    ("Indonesian", "Indonesian"),
    ("Iranian, Persian", "Iranian, Persian"),
    ("Iraqi", "Iraqi"),
    ("Irish", "Irish"),
    ("Manx", "Manx"),
    ("Israeli", "Israeli"),
    ("Italian", "Italian"),
    ("Jamaican", "Jamaican"),
    ("Japanese", "Japanese"),
    ("Channel Island", "Channel Island"),
    ("Jordanian", "Jordanian"),
    ("Kazakhstani, Kazakh", "Kazakhstani, Kazakh"),
    ("Kenyan", "Kenyan"),
    ("I-Kiribati", "I-Kiribati"),
    ("North Korean", "North Korean"),
    ("South Korean", "South Korean"),
    ("Kuwaiti", "Kuwaiti"),
    ("Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz", "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz"),
    ("Lao, Laotian", "Lao, Laotian"),
    ("Latvian", "Latvian"),
    ("Lebanese", "Lebanese"),
    ("Basotho", "Basotho"),
    ("Liberian", "Liberian"),
    ("Libyan", "Libyan"),
    ("Liechtenstein", "Liechtenstein"),
    ("Lithuanian", "Lithuanian"),
    ("Luxembourg, Luxembourgish", "Luxembourg, Luxembourgish"),
    ("Macanese, Chinese", "Macanese, Chinese"),
    ("Macedonian", "Macedonian"),
    ("Malagasy", "Malagasy"),
    ("Malawian", "Malawian"),
    ("Malaysian", "Malaysian"),
    ("Maldivian", "Maldivian"),
    ("Malian, Malinese", "Malian, Malinese"),
    ("Maltese", "Maltese"),
    ("Marshallese", "Marshallese"),
    ("Martiniquais, Martinican", "Martiniquais, Martinican"),
    ("Mauritanian", "Mauritanian"),
    ("Mauritian", "Mauritian"),
    ("Mahoran", "Mahoran"),
    ("Mexican", "Mexican"),
    ("Micronesian", "Micronesian"),
    ("Moldovan", "Moldovan"),
    ("Monégasque, Monacan", "Monégasque, Monacan"),
    ("Mongolian", "Mongolian"),
    ("Montenegrin", "Montenegrin"),
    ("Montserratian", "Montserratian"),
    ("Moroccan", "Moroccan"),
    ("Mozambican", "Mozambican"),
    ("Burmese", "Burmese"),
    ("Namibian", "Namibian"),
    ("Nauruan", "Nauruan"),
    ("Nepali, Nepalese", "Nepali, Nepalese"),
    ("Dutch, Netherlandic", "Dutch, Netherlandic"),
    ("New Caledonian", "New Caledonian"),
    ("New Zealand, NZ", "New Zealand, NZ"),
    ("Nicaraguan", "Nicaraguan"),
    ("Nigerien", "Nigerien"),
    ("Nigerian", "Nigerian"),
    ("Niuean", "Niuean"),
    ("Norfolk Island", "Norfolk Island"),
    ("Northern Marianan", "Northern Marianan"),
    ("Norwegian", "Norwegian"),
    ("Omani", "Omani"),
    ("Pakistani", "Pakistani"),
    ("Palauan", "Palauan"),
    ("Palestinian", "Palestinian"),
    ("Panamanian", "Panamanian"),
    ("Papua New Guinean, Papuan", "Papua New Guinean, Papuan"),
    ("Paraguayan", "Paraguayan"),
    ("Peruvian", "Peruvian"),
    ("Philippine, Filipino", "Philippine, Filipino"),
    ("Pitcairn Island", "Pitcairn Island"),
    ("Polish", "Polish"),
    ("Portuguese", "Portuguese"),
    ("Puerto Rican", "Puerto Rican"),
    ("Qatari", "Qatari"),
    ("Réunionese, Réunionnais", "Réunionese, Réunionnais"),
    ("Romanian", "Romanian"),
    ("Russian", "Russian"),
    ("Rwandan", "Rwandan"),
    ("Barthélemois", "Barthélemois"),
    ("Saint Helenian", "Saint Helenian"),
    ("Kittitian or Nevisian", "Kittitian or Nevisian"),
    ("Saint Lucian", "Saint Lucian"),
    ("Saint-Martinoise", "Saint-Martinoise"),
    ("Saint-Pierrais or Miquelonnais", "Saint-Pierrais or Miquelonnais"),
    ("Saint Vincentian, Vincentian", "Saint Vincentian, Vincentian"),
    ("Samoan", "Samoan"),
    ("Sammarinese", "Sammarinese"),
    ("São Toméan", "São Toméan"),
    ("Saudi, Saudi Arabian", "Saudi, Saudi Arabian"),
    ("Senegalese", "Senegalese"),
    ("Serbian", "Serbian"),
    ("Seychellois", "Seychellois"),
    ("Sierra Leonean", "Sierra Leonean"),
    ("Singaporean", "Singaporean"),
    ("Sint Maarten", "Sint Maarten"),
    ("Slovak", "Slovak"),
    ("Slovenian, Slovene", "Slovenian, Slovene"),
    ("Solomon Island", "Solomon Island"),
    ("Somali, Somalian", "Somali, Somalian"),
    ("South African", "South African"),
    (
        "South Georgia or South Sandwich Islands",
        "South Georgia or South Sandwich Islands",
    ),
    ("South Sudanese", "South Sudanese"),
    ("Spanish", "Spanish"),
    ("Sri Lankan", "Sri Lankan"),
    ("Sudanese", "Sudanese"),
    ("Surinamese", "Surinamese"),
    ("Svalbard", "Svalbard"),
    ("Swazi", "Swazi"),
    ("Swedish", "Swedish"),
    ("Swiss", "Swiss"),
    ("Syrian", "Syrian"),
    ("Chinese, Taiwanese", "Chinese, Taiwanese"),
    ("Tajikistani", "Tajikistani"),
    ("Tanzanian", "Tanzanian"),
    ("Thai", "Thai"),
    ("Timorese", "Timorese"),
    ("Togolese", "Togolese"),
    ("Tokelauan", "Tokelauan"),
    ("Tongan", "Tongan"),
    ("Trinidadian or Tobagonian", "Trinidadian or Tobagonian"),
    ("Tunisian", "Tunisian"),
    ("Turkish", "Turkish"),
    ("Turkmen", "Turkmen"),
    ("Turks and Caicos Island", "Turks and Caicos Island"),
    ("Tuvaluan", "Tuvaluan"),
    ("Ugandan", "Ugandan"),
    ("Ukrainian", "Ukrainian"),
    ("Emirati, Emirian, Emiri", "Emirati, Emirian, Emiri"),
    ("British, UK", "British, UK"),
    ("American", "American"),
    ("American", "American"),
    ("Uruguayan", "Uruguayan"),
    ("Uzbekistani, Uzbek", "Uzbekistani, Uzbek"),
    ("Ni-Vanuatu, Vanuatuan", "Ni-Vanuatu, Vanuatuan"),
    ("Venezuelan", "Venezuelan"),
    ("Vietnamese", "Vietnamese"),
    ("British Virgin Island", "British Virgin Island"),
    ("U.S. Virgin Island", "U.S. Virgin Island"),
    (
        "Wallis and Futuna, Wallisian or Futunan",
        "Wallis and Futuna, Wallisian or Futunan",
    ),
    ("Sahrawi, Sahrawian, Sahraouian", "Sahrawi, Sahrawian, Sahraouian"),
    ("Yemeni", "Yemeni"),
    ("Zambian", "Zambian"),
    ("Zimbabwean", "Zimbabwean"),
)
